name: Node.js CI

on:
  push:

jobs:
  build:
    name: "Build Learning tool server application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Run jobs
        working-directory: ./server
        run: | 
        npm ci
        npm run build --if-present
        npm run
        npm test
